name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libgl-dev
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --parallel
    - name: Test
      run: ctest --test-dir build --output-on-failure
    - name: Upload binary
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: nesemu-linux
        path: build/nesemu
